---
title: "steps"
output: html_document
editor_options: 
  chunk_output_type: console
---

module load hdf5
module load R/3.6.0
R

```{r setup, include=FALSE, cache=FALSE}
analysis_name <- "analysis.seurat/" # change this

ifelse(dir.exists("/mnt/scc/project_workspace/"),
       cremwd <- "/mnt/scc/",
       cremwd <- "/restricted/projectnb/crem-bioinfo/")
calculations_path <- file.path(cremwd, "project_workspace/18_03_21_kostas/calculations/analysis", analysis_name, "/")
rds_path <- file.path(calculations_path, "/rds/")
plots_path <- file.path(calculations_path, "/plots/")

dir.create(rds_path, recursive = T)
dir.create(plots_path, recursive = T)

library(tidyverse)
library(Seurat)
library(Matrix)
library(matrixStats) #rowVars
library(magrittr)
library(dplyr)
library(RColorBrewer)
library(kableExtra)
library(data.table) # getting counts
library(knitr)
library(clustree)
library(patchwork)
library(harmony)

```

```{r}
sc <- readRDS("/restricted/projectnb/crem-bioinfo/project_workspace/18_03_21_kostas/calculations/analysis.seurat/sc.Rds")

```

```{r GSA}
table(sc$annot)
table(sc$orig.ident)
fmas <- function(sc, res) {
    Idents(sc) <- res
    file_out <- paste0(calculations_path, "DEG.", res, ".xlsx")
    seurat.markers <- FindAllMarkers(sc, test.use = "MAST", only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.1, verbose = F)
    seurat.markers.summary <- as.data.frame(seurat.markers %>% group_by(cluster) %>% dplyr::filter(p_val_adj < 0.05) %>% top_n(20, abs(avg_logFC)))
    openxlsx::write.xlsx(seurat.markers, file_out, zoom = 100, asTable = TRUE, tableStyle = "none", rowNames = F)
    return(list(all = seurat.markers, top = seurat.markers.summary))
}
resDEG <- "annot"
sc.markers.mas.res <- fmas(sc, resDEG)
saveRDS(sc.markers.mas.res, paste0(rds_path, "sc.markers.mas.", resDEG, ".Rds"))

Idents(sc) <- "annot"
fmas.pair <- function(sc, res, id1, id2, subsets, suffix) {
    file_out <- paste0(calculations_path, "DEG.pairwise.", suffix, ".", res, ".xlsx")
    seurat.markers <- FindMarkers(sc, test.use = "MAST", only.pos = FALSE, min.pct = 0.10, logfc.threshold = 0, verbose = F, group.by = res,  ident.1 = id1, ident.2 = id2, subset.ident = subsets)
    seurat.markers.summary <- as.data.frame(seurat.markers) %>%  rownames_to_column('gene') %>% dplyr::filter(p_val_adj < 0.05) %>% dplyr::arrange(desc(avg_logFC)) %>% dplyr::filter(row_number() %in% 1:20 | row_number() %in% (n()-19):n())
    openxlsx::write.xlsx(seurat.markers, file_out, zoom = 100, asTable = TRUE, tableStyle = "none", rowNames = T)
    return(list(all = seurat.markers, top = seurat.markers.summary))
}
mas.pair1 <- fmas.pair(sc, "annot", id1 = "C11", id2 = "B2", subsets = NULL, suffix = "C11_vs_B2")
mas.pair1 <- mas.pair1[[1]] %>% rownames_to_column("row.names")

library(fgsea)
library(msigdbr)
set.seed(42)
msig.H <- msigdbr(species = "Homo sapiens", category = "H")
names(table(msig.H$gs_name))
msig.H <- as.data.frame(msig.H[,c(2, 5)])
msig.H <- split(msig.H$human_gene_symbol, msig.H$gs_name)

ranks1 <- mas.pair1$avg_logFC
names(ranks1) <- mas.pair1$row.names
fgsea.1 <- fgsea(pathways = msig.H , 
                        stats = ranks1,
                        minSize=5,
                        maxSize=500,
                        nperm = 1000)
head(fgsea.1[order(NES, decreasing = T), ])
tail(fgsea.1[order(NES, decreasing = T), ])
head(fgsea.1[order(pval), ])
data.table::fwrite(fgsea.1[order(pval), ], file=paste0(calculations_path, "fgsea_C11_vs_B2_hallmarks.tsv"), sep="\t", sep2=c("", " ", ""))

 
keep.gs <- names(table(grep("APOPTOSIS|MTORC|NFKB|OXYDATIVE_PHOSPORILATION|PI3K|LYSOSO", msigdbr()$gs_name, value = T)))
keep.gs <- filter(keep.gs, )
keep.gs <- keep.gs[-grep("^GSE|_UP$|_DN$", keep.gs)]
msig.custom <- msigdbr(species = "Homo sapiens") %>% filter(gs_name %in% keep.gs)
names(table(msig.custom$gs_name))
msig.custom <- as.data.frame(msig.custom[,c(2, 5)])
msig.custom <- split(msig.custom$human_gene_symbol, msig.custom$gs_name)
fgsea.2 <- fgsea(pathways = msig.custom , 
                        stats = ranks1,
                        minSize=5,
                        maxSize=500,
                        nperm = 1000)
head(fgsea.2[order(NES, decreasing = T), ])
tail(fgsea.2[order(NES, decreasing = T), ])
head(fgsea.2[order(pval), ])
data.table::fwrite(fgsea.2[order(pval), ], file=paste0(calculations_path, "fgsea_C11_vs_B2_selected_gene_sets.tsv"), sep="\t", sep2=c("", " ", ""))

```



```{r plot_heatmap}
# switch to RNA normalized for heatmap visualization
DefaultAssay(sc) <- "RNA"
sc <- NormalizeData(sc)
all.genes <- rownames(sc)
sc <- ScaleData(sc, features = all.genes, vars.to.regress="percent.mito", verbose = F) # default: only scales var.genes, which misses some in heatmap

DefaultAssay(sc) <- "SCT"


mas.pair1 <- readxl::read_excel(paste0(calculations_path, "DEG.pairwise.C11_vs_B2.annot.xlsx")) 
# plot only genes from hallmarks that are DEG in all infected vs ctl
allDEG <- mas.pair1 %>% filter(p_val_adj < 0.05) %>% pull(row.names)
countDEG <- mas.pair1 %>% filter(p_val_adj < 0.05)
table(countDEG$avg_logFC < 0)

# FALSE  TRUE 
#   585  1704 
idx <- msig.H 
idx <- msig.custom 

fgsea <- fgsea.1
fgsea <- fgsea.2
for (i in 1:nrow(fgsea)) {
  genes <- fgsea[i, "leadingEdge"][[1]][[1]]
  height.fig <- (0.12 * length(genes) ) + 1
  g <- DoHeatmap(sc, features = genes, raster = F) + scale_fill_gradientn(colors = c("blue", "white", "red"))
  ggsave(paste0(plots_path, "Heatmaps_SELECTED_GENE_SETS/Hm.", fgsea$pathway[i], ".DEG.pdf"), g, width=7, height=height.fig)
}

# for (i in names(idx)) {
#   genes <- idx[[i]][ idx[[i]] %in% rownames(sc) & idx[[i]] %in% allDEG ]
#   height.fig <- (0.1 * length(genes) ) + 1
#   g <- DoHeatmap(sc, features = genes, raster = F) + scale_fill_gradientn(colors = c("blue", "white", "red"))
#   ggsave(paste0(plots_path, "Hm.", i, ".DEG.pdf"), g, width=7, height=height.fig)
# }
83
14.2
```



```{r save_object}
saveRDS(sc, paste0(rds_path, "sc.Rds"))
```













```{r complex_heatmap}
plot_complex_heatmap <- function(genes, highlight_gene_names, row_names_gp=5) {
  cluster_names <- factor(dge$samples$condition)
  cluster_colors <- setNames( brewer.pal(length(levels(cluster_names)),"Set2"), levels(cluster_names) ) # == cols2, a named vector of color
   ht_manual <- list(
    data = t(scale(t(lcpm[genes,]), center = TRUE, scale = TRUE)[,] ) ,
    top_annotation = HeatmapAnnotation(
      df = data.frame( Condition = cluster_names ),
      col = list( Condition = cluster_colors )
    )
   ) 
  indexes <- match(highlight_gene_names, rownames(ht_manual$data))
  labels <- rownames(ht_manual$data)[indexes] 
  ht_manual$ha <- rowAnnotation( foo = anno_mark(at = indexes, labels = labels), width = unit(1, "cm") + max_text_width(labels) )
  ht_manual$heatmap <- Heatmap(ht_manual$data, 
                               cluster_columns = FALSE, 
                               cluster_rows = TRUE, 
                               show_column_names = FALSE,
                               show_row_names = TRUE,
                               column_names_side = "top",
                               top_annotation = ht_manual$top_annotation,
                               name = "Expression z-score",
                               col = colorRampPalette(rev(brewer.pal(9, "RdBu")))(100),
                               column_title = ht_manual$column_title,
                               heatmap_legend_param = list(
                                 color_bar = "continuous",
                                 legend_direction = "horizontal",
                                 legend_width = unit(4, "cm")
                               ),
                               column_title_gp = gpar(fontsize = 20, fontface = "bold"),
                               row_names_gp = gpar(fontsize = row_names_gp)
  )
  return(ht_manual)
}
allDEG.coef3 <- topTable(efit, coef = 3, number=Inf, p.value = 0.05) %>% pull(SYMBOL)
genes.highlight <- list(
  one = c("TNFAIP8","CSF2","IL6","TNF","CXCL11","CXCL10","EGR1","TNFRSF9","TNFAIP3","RELB","AREG","SQSTM1","IRF1","NFKBIA","NFKB2","CXCL1","NFKBIE","REL","NFKB1","IL23A","CXCL2","GEM","EGR2","CXCL3","RELA","GADD45B","TNFAIP2","TNFSF9","VEGFA"),
  two = c("IRF8","IFIT1","MX1","IRF7","CXCL10","CXCL11","IRF1","ISG15","IRF4")
) # "IRF9" and "IFNAR2" arent DEG
gene.sets <- c("HALLMARK_TNFA_SIGNALING_VIA_NFKB", "HALLMARK_INTERFERON_GAMMA_RESPONSE")
library(ComplexHeatmap)
for (i in 1:2) {
  genes <- rownames(lcpm[idx[[gene.sets[i]]],])[ rownames(lcpm[idx[[gene.sets[i]]],]) %in% allDEG.coef3]
  highlight_gene_names <- genes.highlight[[i]][ genes.highlight[[i]] %in% genes]
  ht <- plot_complex_heatmap(genes, highlight_gene_names)
  height.fig <- (0.05 * length(genes) ) + 1
  pdf(paste0(plots_path, "Hm.", gene.sets[i], ".DEG.lcpm.zscore.byrow.col2.highlighted.pdf"), width=4, height=height.fig)
  draw(ht$heatmap + ht$ha, heatmap_legend_side = "top")
  dev.off()
}
# Sys.setenv(DISPLAY="10.48.225.54:131.0")


table(sc$orig.ident)
table(sc$annot)
msig <- scan(paste0(cremwd, "/reference_data/gene_sets/lung.matur.differ.MSig.txt"), what="", sep="\n") # Read in the data
msig <- sapply(msig, function(k) gsub(",$", "", k))
msig <- strsplit(msig, ",[[:space:]]+")  # Separate elements by a comma and one or more whitepace
names(msig) <- sapply(msig, `[[`, 1)  # subset the first vector element and set it as the list element name
msig <- lapply(msig, `[`, -1) # Remove the first vector element from each list element
msig <- msig[1:2]
msig <- unlist(msig)
genes.plot <- unique(c( "SFTPC", msig, "SFTPB", "SFTPD", "SFTPA1", "SFTPA2", "NKX2-1", "MKI67", "TM4SF1" ,"SQSTM1", "KRT5", "SCGB1A1", "FOXJ1","PTPRC", "CDH5", "EPCAM", "COL1A1","ATP6V0B"  ))
DefaultAssay(sc) <- "RNA"
Idents(sc) <- "annot"
project <- sub(".*workspace/(.*tas).*", "\\1", plots_path)
p <- DotPlot(sc, features = rev(genes.plot),  assay = "RNA") 
p <- p & ggmin::theme_powerpoint()  & RotatedAxis() & theme(axis.title.x = element_blank(), axis.title.y = element_blank())
ggsave(paste0(plots_path, "Dot.JCL.", project, ".pdf"), p, width = 10, height = 4.5)
p <- VlnPlot(sc, features = genes.plot, group.by = "orig.ident", pt.size = 0.1, assay = "RNA")
p <- p & ggmin::theme_powerpoint()  & RotatedAxis() & theme(axis.title.x = element_blank(), axis.title.y = element_blank())
ggsave(paste0(plots_path, "Vln.JCL.", project, ".pdf"), p, width = 15, height = 15)

DefaultAssay(sc) <- "SCT"
g <- DimPlot(sc, group.by = "orig.ident") + ggmin::theme_powerpoint()
ggsave(paste0(plots_path, "UMAP.color.by.orig.ident.pdf"), g)

p <- FeaturePlot(sc, features = "RPL39", cols = c("#f0f0f0", brewer.pal(9,"OrRd")) ) 
p <- p & ggmin::theme_powerpoint() & NoAxes() & NoLegend()
ggsave(paste0(plots_path, "UMAP.RPL39.pdf"), p)

sc[["percent.RP"]] <- PercentageFeatureSet(sc, pattern = "^RP")
p <- FeaturePlot(sc, features = "percent.RP", cols = c("#f0f0f0", brewer.pal(9,"OrRd")) ) 
p <- p & ggmin::theme_powerpoint() & NoAxes() & NoLegend()
ggsave(paste0(plots_path, "UMAP.percent.RP.pdf"), p)

p <- FeaturePlot(sc, features = "percent.mito", cols = c("#f0f0f0", brewer.pal(9,"OrRd")) ) 
p <- p & ggmin::theme_powerpoint() & NoAxes() & NoLegend()
ggsave(paste0(plots_path, "UMAP.percent.mito.pdf"), p)

summary(sc$percent.RP)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 4.743   9.645  14.731  18.143  25.640  50.148 

p <- DimPlot(sc, cells.highlight = WhichCells(sc, expression = `percent.RP` > 25) ) + ggmin::theme_powerpoint() + ggtitle("Highlighted cells percent.RP > 25") 
ggsave(paste0(plots_path, "UMAP.RP.25.highlighted.pdf"), p, width = 8, height = 7)

grouping <- "res.1";  p1 <- DimPlot(sc, group.by = grouping, label = T) + labs(title = grouping) 
grouping <- "res.1.25"; p2 <- DimPlot(sc, group.by = grouping, label = T) + labs(title = grouping) 
grouping <- "res.1.5";  p3 <- DimPlot(sc, group.by = grouping, label = T) + labs(title = grouping)
grouping <- "res.1.75"; p4 <- DimPlot(sc, group.by = grouping, label = T) + labs(title = grouping) 
grouping <- "res.0.5";  p5 <- DimPlot(sc, group.by = grouping, label = T) + labs(title = grouping)
grouping <- "res.0.75"; p6 <- DimPlot(sc, group.by = grouping, label = T) + labs(title = grouping)
p <- p5 + p6 + p1 + p2 + p3 + p4 
p <- p & ggmin::theme_powerpoint() & NoAxes() & NoLegend()
ggsave(paste0(plots_path, "UMAP.clust.pdf"), p, width = 10, height = 7)

####################################
########  REPEAT HALLMARKS ANALYSIS
########  WITHOUT RP HIGH CELLS
####################################

scs <- subset(sc, cells = WhichCells(sc, expression = `percent.RP` < 25) )
table(scs$orig.ident)

mas.pair2 <- fmas.pair(scs, "annot", id1 = "C11", id2 = "B2", subsets = NULL, suffix = "C11_vs_B2.subset")
mas.pair2 <- mas.pair2[[1]] %>% rownames_to_column("row.names")

library(fgsea)
library(msigdbr)
set.seed(42)
msig.H <- msigdbr(species = "Homo sapiens", category = "H")
names(table(msig.H$gs_name))
msig.H <- as.data.frame(msig.H[,c(2, 5)])
msig.H <- split(msig.H$human_gene_symbol, msig.H$gs_name)

ranks2 <- mas.pair2$avg_logFC
names(ranks2) <- mas.pair2$row.names
fgsea.4 <- fgsea(pathways = msig.H , 
                        stats = ranks2,
                        minSize=5,
                        maxSize=500,
                        nperm = 1000)
head(fgsea.4[order(NES, decreasing = T), ])
tail(fgsea.4[order(NES, decreasing = T), ])
head(fgsea.4[order(pval), ])
data.table::fwrite(fgsea.4[order(pval), ], file=paste0(calculations_path, "fgsea_C11_vs_B2_subset.RPlow_hallmarks.tsv"), sep="\t", sep2=c("", " ", ""))

allDEG <- mas.pair2 %>% filter(p_val_adj < 0.05) %>% pull(row.names)
idx <- msig.H 

dir.create(paste0(plots_path, "Heatmaps_HALLMARKS_subset_RP_low"), recursive = T)

fgsea <- fgsea.4
for (i in 1:nrow(fgsea)) {
  genes <- fgsea[i, "leadingEdge"][[1]][[1]]
  height.fig <- (0.12 * length(genes) ) + 1
  g <- DoHeatmap(scs, features = genes, raster = F) + scale_fill_gradientn(colors = c("blue", "white", "red"))
  ggsave(paste0(plots_path, "Heatmaps_HALLMARKS_subset_RP_low/Hm.", fgsea$pathway[i], ".DEG.pdf"), g, width=7, height=height.fig)

}
table(scs$annot)

DefaultAssay(sc) <- "SCT"
p <- FeaturePlot(sc, features = "MKI67", cols = c("#f0f0f0", brewer.pal(9,"OrRd")) ) 
p <- p & ggmin::theme_powerpoint() & NoAxes() & NoLegend()
ggsave(paste0(plots_path, "UMAP.18_03_21_kostas.MKI67.pdf"), p)

DefaultAssay(sc) <- "SCT"
g <- DimPlot(sc, group.by = "annot") + ggmin::theme_powerpoint()
ggsave(paste0(plots_path, "UMAP.18_03_21_kostas.color.annot.pdf"), g)

```



```{r}
library(tidyverse)
fgsea.1 <- read.table(paste0(calculations_path, "fgsea_C11_vs_B2_hallmarks.tsv"), sep="\t", header = T)

head(fgsea.1)
colnames(fgsea.1)
fgsea.1[1:3,1:3]
fgsea.1.sub <- fgsea.1 %>% filter(NES > 0)  %>% head(10) 
fgsea.1.sub$Term <- fgsea.1.sub$pathway
fgsea.1.sub$Significance <- ifelse(fgsea.1.sub$padj < 0.05, "FDR < 0.05", "Not sig.")
fgsea.1.sub$Significance <- factor(fgsea.1.sub$Significance, level = c("FDR < 0.05", "Not sig."))
fgsea.1.sub$Term <- sub("HALLMARK_", "", fgsea.1.sub$Term)
fgsea.1.sub$Term <- gsub("_", " ", fgsea.1.sub$Term)
fgsea.1.sub$`-log(P-value)` <- -log(fgsea.1.sub$pval)
p <- ggplot(fgsea.1.sub, aes(x=reorder(Term, `-log(P-value)`), y=`-log(P-value)`,fill=Significance)) +
  geom_bar(stat='identity') +
  coord_flip() + 
  theme_minimal() +
  theme(axis.text=element_text(size=15, face = "bold"), axis.title.y=element_blank()) +
  scale_fill_manual(name = "Significance",values = setNames( c("grey20", "grey"), c("FDR < 0.05", "Not sig.") )) +
  ylab("Evidence of enrichment [-log(P value)]") 
ggsave(paste0(plots_path, "/Bp.FGSEA.top10.enriched.Hallmarks.C11vsB2.logp.pdf"), p, width = 9, height = 4)

p <- ggplot(fgsea.1.sub, aes(x=reorder(Term, `NES`), y=`NES`,fill=Significance)) +
  geom_bar(stat='identity') +
  coord_flip() + 
  theme_minimal() +
  theme(axis.text=element_text(size=15, face = "bold"), axis.title.y=element_blank()) +
  scale_fill_manual(name = "Significance",values = setNames( c("grey20", "grey"), c("FDR < 0.05", "Not sig.") )) +
  ylab("Evidence of enrichment [Normalized enrichement score]") 
ggsave(paste0(plots_path, "/Bp.FGSEA.top10.enriched.Hallmarks.C11vsB2.NES.pdf"), p, width = 9, height = 4)


```


```{r}
colnames(sc[[]])
msig <- scan(paste0(cremwd, "/reference_data/gene_sets/lung.matur.differ.MSig.txt"), what="", sep="\n") # Read in the data
msig <- sapply(msig, function(k) gsub(",$", "", k))
msig <- strsplit(msig, ",[[:space:]]+")  # Separate elements by a comma and one or more whitepace
names(msig) <- sapply(msig, `[[`, 1)  # subset the first vector element and set it as the list element name
msig <- lapply(msig, `[`, -1) # Remove the first vector element from each list element

sc <- AddModuleScore(sc, features = msig, name = names(msig), search = T) # searches for synonims
sc <- AddMetaData(sc, sc[[paste0(names(msig), 1:length(names(msig)))]], col.name = names(msig))
for(i in paste0(names(msig), 1:length(names(msig)))) {
  sc[[i]] <- NULL
}

table(sc$annot)
sc$annot3 <- factor(sc$annot)
table(sc$annot3, useNA = "ifany")
levels(sc$annot3) <- sub("B2","tdT/WT",levels(sc$annot3))
levels(sc$annot3) <- sub("C11","I73T/tdT",levels(sc$annot3))

# saveRDS(sc, paste0(rds_path, "sc.w.msig.Rds"))
sc <- readRDS(paste0(rds_path, "sc.w.msig.Rds"))
vln.genes <- c("SFTPC", "SFTPB", "NKX2-1")
p <- VlnPlot(sc, features = vln.genes, group.by = "annot3", pt.size = 0.1, assay = "RNA")
p <- p & ggmin::theme_powerpoint()  & RotatedAxis() & theme(axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank())
ggsave(paste0(plots_path, "Vln.18_03_21_kostas.114.a.pdf"), p, width = 12, height = 3.5)

p <- VlnPlot(sc, features = c("iAEC2.differentiation.8genes", "S.Score", "G2M.Score", "MKI67"), group.by = "annot3", pt.size = 0.1, assay = "RNA")
p <- p & ggmin::theme_powerpoint()  & RotatedAxis() & theme(axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank())
ggsave(paste0(plots_path, "Vln.18_03_21_kostas.114.signatures.pdf"), p, width = 12, height = 6)

p <- FeaturePlot(sc, features = vln.genes ) 
p <- p & ggmin::theme_powerpoint() & NoAxes() 
ggsave(paste0(plots_path, "UMAP.18_03_21_kostas.114.b.pdf"), p, width = 7, height = 6)
```

```{r}
mas.pair1 <- readxl::read_excel(paste0(calculations_path, "DEG.pairwise.C11_vs_B2.annot.xlsx")) 
# plot only genes from hallmarks that are DEG in all infected vs ctl
mas.pair1 %>% filter(row.names %in% c("SFTPC", "SFTPB", "NKX2-1", "MKI67"))

table(sc$annot3)

for (i in levels(scs$annot3) ) {
  t.test(scs$iAEC2.differentiation.8genes  ~ scs$annot3 == i)
}
t.rst <- t.test(sc$iAEC2.differentiation.8genes  ~ sc$annot3 )
t.rst1 <- t.test(sc$S.Score  ~ sc$annot3 )
t.rst2 <- t.test(sc$G2M.Score  ~ sc$annot3 )

writeLines(capture.output(print(list(t.rst, t.rst1, t.rst2))), 
           con = file(paste0(calculations_path, "enrichment.AT2.signature.and.cellcycle.t.test.txt")))



fmas.pair.final <- function(sc, res, id1, id2, subsets, suffix) {
    file_out <- paste0(calculations_path, "DEG.pairwise.", suffix, ".", res, ".pct.0.10.logfc.0.15.FDR.0.05.xlsx")
    seurat.markers <- FindMarkers(sc, test.use = "MAST", only.pos = FALSE, min.pct = 0.10, logfc.threshold = 0.15, verbose = F, group.by = res,  ident.1 = id1, ident.2 = id2, subset.ident = subsets)
    seurat.markers.summary <- as.data.frame(seurat.markers) %>%  rownames_to_column('gene') %>% dplyr::filter(p_val_adj < 0.05) %>% dplyr::arrange(desc(avg_logFC)) 
    openxlsx::write.xlsx(seurat.markers.summary, file_out, zoom = 100, asTable = TRUE, tableStyle = "none", rowNames = T)
    return(list(all = seurat.markers, top = seurat.markers.summary))
}
mas.pair1.final <- fmas.pair.final(sc, "annot", id1 = "C11", id2 = "B2", subsets = NULL, suffix = "C11_vs_B2")
mas.pair1.final[[2]] %>%   
  summarise(upDEG = sum(avg_logFC>0),
         dnDEG = sum(avg_logFC<0))
#   upDEG dnDEG
# 1   326   747
```